[build] 
    command = "yarn build"
    publish = "build"

[[redirects]]
    from = "/api/v1/*"
    to = "https://get-cat-back.onrender.com/:splat"
    status = 200
    
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200